### ISSUE TITLE
Rebase command can not trigger test check workflow

### ISSUE THREAD

**Issue by jolestar** [cirrus-actions/rebase#65]
the RP after rebase by /rebase command can not trigger test check workflow

**Comment by sebastianvarela** [comment]
+1
I tryied to pass a custom token:

```

**Comment by gurrpi** [comment]
+1

**Comment by fkorotkov** [comment]
This is a weird Actions limitation that one workflow can't trigger another one. See [this community post](https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/33) for more details. I don't believe there is a viable workaround at the moment. On a bright side it does work with 3rdparty CIs like Travis, Circle and Cirrus.

**Comment by starsep** [comment]
I tried adding
```
on:
  workflow_run:
    workflows: ["Automatic Rebase"]
    types: 
      - completed
```
to test workflow, it is run on default branch not within context of rebased pull request.

Documentation seemed promising
> This event occurs when a workflow run is requested or completed, and allows you to execute a workflow based on the finished result of another workflow. For example, if your pull_request workflow generates build artifacts, you can create a new workflow that uses workflow_run to analyze the results and add a comment to the original pull request.

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_run

But article about this feature clearly states that
> Runs triggered by the workflow_run event always use the default branch for the repository

https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/

**Comment by jolestar** [comment]
> This is a weird Actions limitation that one workflow can't trigger another one. See [this community post](https://github.community/t/triggering-a-new-workflow-from-another-workflow/16250/33) for more details. I don't believe there is a viable workaround at the moment. On a bright side it does work with 3rdparty CIs like Travis, Circle and Cirrus.

this action https://github.com/Label305/AutoRebase can auto rebase and trigger CI workflow by use a personal github token.

I try to use a personal github token for cirrus-actions/rebase, but not work.

**Comment by spaze** [comment]
I've worked around the issue by letting my GitHub Actions test workflow run also in pull request review events:

```
on: [push, pull_request_review]
```

Running `/rebase` will rebase the branch but the PR will be stuck waiting for the test workflow to finish but it doesn't even start (that's this issue). Approving a review will start it and run it again and then the test workflow finishes 🎉
GitHub can also optionally dismiss an existing review automatically prompting someone to approve the change again triggering the test workflow.

Not perfect but it works for me. Thank you for this rebase action 👍

**Comment by spaze** [comment]
I've now create a PR with that workaround description because maybe more people might find it useful.

**Comment by walterholohan** [comment]
Do you think this will be fixed anytime soon by the GHA team?

**Comment by jackton1** [comment]
@walterholohan Fixed here https://github.com/cirrus-actions/rebase/pull/70

**Comment by walterholohan** [comment]
@jackton1 I updated the action yaml file to
```
on:
  issue_comment:
    types: [created]
name: Automatic Rebase
jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo,
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token.
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
```
where `secrets.GH_PAT` is a PAT that I have setup. However this did not solve the issue. After a successful rebase by the`cirrus-actions/rebase@1.4` action it did not trigger a new check workflow. Am I missing something from the above snippet?

**Comment by jackton1** [comment]
@walterholohan it seems actions/checkout@v2 fails with the default github.token

**Comment by walterholohan** [comment]
@jackton1 ive changed to the above suggestion but still no luck. The rebase completed successfully but the actions did not get triggered. Does the PAT need certain permissions? Maybe its missing something.

**Comment by jackton1** [comment]
@walterholohan Try again using 
![Screen Shot 2021-01-11 at 7 49 19 PM](https://user-images.githubusercontent.com/17484350/104255043-2a5b4300-5446-11eb-8d35-73d1df027b4c.png)

Note for workflows that modify github actions you can enable

![Screen Shot 2021-01-11 at 7 50 39 PM](https://user-images.githubusercontent.com/17484350/104255113-4fe84c80-5446-11eb-9374-2f784b4429c7.png)

**Comment by walterholohan** [comment]
All good, I got it working. `persist-credentials: false` needs to be set otherwise it wont work

**Comment by walterholohan** [comment]
Thank you, It was an issue on my end. I was trying to test this out in a PR but when I triggered a rebase by adding a `/rebase` comment it what using the workflow from the develop branch instead of the PR. Once I merged the PR it worked. I also added `persist-credentials: false` to the checkout action
